server:
  port: 8081

spring:
  application:
    name: store-admin

  rabbitmq:
    host: laoh.tplinkdns.com
    port: 5672
    username: admin
    password: admin123!

  datasource:
    url: jdbc:mysql://laoh.tplinkdns.com:3306/delivery?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1013

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate #엔티티가 테이블과 매핑이 되지 않으면 애플리케이션이 실행이 되지 않도록 설정하는 것임.
